version: '2'
services:
  db:
    image: couchdb:1.7.1
    ports:  
      - "35984:5984"
    volumes:
      - ./data:/usr/local/var/lib/couchdb
    network_mode: bridge
  couchbackup:
    build: ./docker
    links:
      - db
    network_mode: bridge
